const targetAccounts = [

    'https://www.instagram.com/superturfinc/',
    'https://www.instagram.com/restorationlane/',
    'https://www.instagram.com/delraymag/',
    'https://www.instagram.com/renovatewiththeroots/',
    'https://www.instagram.com/mmwooddesigns/',
    'https://www.instagram.com/sassafraswpb/',
    'https://www.instagram.com/realtordotcom/',
    'https://www.instagram.com/sloans_southflorida/',
    'https://www.instagram.com/narresearch/',
    'https://www.instagram.com/bocalifemag/',
    'https://www.instagram.com/oldschoolsquaredelray/',
    'https://www.instagram.com/trustscout/',
    'https://www.instagram.com/exteriors_of_insta/',
    'https://www.instagram.com/investorsandinvesting/',
    'https://www.instagram.com/investwithrevival/',
    'https://www.instagram.com/serenitynowstaging/',
    'https://www.instagram.com/motivation.king101/',
    'https://www.instagram.com/allthingsrealestate/',
    'https://www.instagram.com/thehometeamkw',
    'https://www.instagram.com/the_business_essentials/',
    'https://www.instagram.com/investorsthink/',
    'https://www.instagram.com/propertyfindings/',
    'https://www.instagram.com/himmelsellshomes',
    'https://www.instagram.com/remaxadamcontos/',
    'https://www.instagram.com/cerverare',
    'https://www.instagram.com/6amsuccess/',
    'https://www.instagram.com/thebillionaireplaybook/',
    'https://www.instagram.com/livingproof.photography/',
    'https://www.instagram.com/megangribblehome',
    'https://www.instagram.com/jillszedergables/',
    'https://www.instagram.com/flippingahouse/',
    'https://www.instagram.com/landscapeartinc/',
    'https://www.instagram.com/thesalemteam/',
    'https://www.instagram.com/rncbuilders/',
    'https://www.instagram.com/apartmentinvestingjourney/',


];

module.exports = targetAccounts;

/*LIST TARGETING MEN ON WOMENS PAGES - ONLYFANS
    'https://www.instagram.com/mandi_lynn_bbw/',
    'https://www.instagram.com/therealnatashatosini/',
    'https://www.instagram.com/jaidexoxo_/',
    'https://www.instagram.com/ivykiaraofficial/',
    'https://www.instagram.com/tatted.mama44/',
    'https://www.instagram.com/officialmakaylaalt/',
    'https://www.instagram.com/amberleighhh/',
    'https://www.instagram.com/devin.meow/',
    'https://www.instagram.com/jessicakes33/',
    'https://www.instagram.com/jessicacakes2/',
    'https://www.instagram.com/jessicafitcake/',
    'https://www.instagram.com/millenawhite/',
    'https://www.instagram.com/_lucky_ladybird/',
    'https://www.instagram.com/millena_white/',
    'https://www.instagram.com/missjessarhodes/',
    'https://www.instagram.com/fierysireniv/',
    'https://www.instagram.com/egoistqaa/',
    'https://www.instagram.com/liubov_kalish/',
    'https://www.instagram.com/lsdiamonds69/',
    */

/* 'https://www.instagram.com/boandtee/',
    'https://www.instagram.com/revolve/',
    'https://www.instagram.com/revolvebeauty/',
    'https://www.instagram.com/maccosmetics/',
    'https://www.instagram.com/ohpolly/',
    'https://www.instagram.com/ohpollyswim/',
    'https://www.instagram.com/pallascouture/',
    'https://www.instagram.com/pallascollective/',
    'https://www.instagram.com/studio.albus/',
    'https://www.instagram.com/seduction_la/',
    'https://www.instagram.com/fuckologyofficial/',
    'https://www.instagram.com/betchwithnolife/',
    'https://www.instagram.com/basic/',
    'https://www.instagram.com/bipolar_girlfriend_/',
    'https://www.instagram.com/ohmboutique/',
    'https://www.instagram.com/yourbreakupbestie/',
    'https://www.instagram.com/sahirajewelrydesign/',
    'https://www.instagram.com/okb_int/',
    'https://www.instagram.com/cottononbody/',
    'https://www.instagram.com/lv_perfection_medspa/',
    'https://www.instagram.com/berrybeachyswimwear/',
    'https://www.instagram.com/callherdaddy/',
    'https://www.instagram.com/bangn.body/',
    'https://www.instagram.com/lovetrends.shop/',
    'https://www.instagram.com/glossy_zodiac/',
    'https://www.instagram.com/bossbabe.inc/',*/
