let comment = [
	'I underestimated you Michael. Yea, well maybe next time, you better estimate me.  -MichaelScott',
	'Live and let live. Im not familiar with that expression. Its a James Bond.  -MichaelScott',
	'I like this chair, it offers good support and is ErckleNomickly correct.  -MichaelScott',
	'I went to the park tryna feed the pigeons. I guess they all flew west for the winter.  -MichaelScott',
	'They are in for a bitter suprise... I am not to be truffled with.  -MichaelScott',
	'Remember, They are trying to make me an escape goat.  -MichaelScott',
	'You all encouraged it! You were complissit! You are all successories!  -MichaelScott',
	'This is like the Blair ..Witch ..Hunt ..Project.  -MichaelScott',
	'Jim halpert is smudge and arrogant... I think you mean smug.  Theres that arrogance.  -MichaelScott',
	'And it is up to me... to get rid of the curse... that hit meredith with my car.  -MichaelScott',
	'Nailed it!  -andybernard',
	'Dont drop the soap! Dont drop the soap!  -Prisonmike',
	'And you my friend, would be... Da Bell-Of-Da-Ball  -PrisonMike',
	"You know, stuff like.. 'Fleece it out' and 'Going mach five.'  -DarrylPhilbin",
	'Well well well, how the turntables.  -MichaelScott',
	'Webster’s Dictionary defines wedding as.. the fusing of two metals with a hot torch.  -MichaelScott',
	'Who is Justice Beaver?  -DwightSchrute',
	'I am faster than 80 percent of all snakes.  -DwightSchrute',
	'Bears...Beats...Battlestar Galactica.  -JimHalpert',
	'Hi, I’m Date Mike. Nice to meet me.  -MichaelScott',
	'Which Bear is Best?  -DwightSchrute',
	"Sometimes I start a sentence, without knowing where it's going. I just hope I find it along the way.  -MichaelScott",
	'Bread is the paper of the food industry. You write your sandwich on it.  -DwightSchrute',
	'Ain’t no party like a Scranton party cause a Scranton party don’t stop!  -MichaelScott',
	'Bob Vance, Vance Refrigeration.   -BobVance',
	'Break me off a piece of that app-le-sauce.   -AndyBernard',
	"Now, let's say you and I go toe-to-toe on bird law... and see who comes out the victor.  -CharlieKelly",
	'We are at Threat Level Midnight.  -MichaelScott',
	'Cause... Science is a liar, sometimes.   -FatMac',
	'I love my employees even though I hit one of you with my car.  -MichaelScott',
	'When the king of Nigeria emails you directly, asking for help, you help.  -MichaelScott',
	'Rit-dit-dit-doooo!   -AndyBernard',
	'This is ham, soaked in rum... RUM-HAM!   -FrankReynolds',
	"Shadynasty's Jazz Club.   -FrankReynolds",
	'Fight Milk! The first alcoholic dairy based protein drink for bodyguards!   -Charliekelly',
	'Parkor... Hardcore Parkor!  -MichaelScott',
	'Jim and I are great friends. We hang out a ton, mostly at work.  -MichaelScott',
	"White-collar and blue-collar. I don’t see it that way... Cause I'm collar blind.  -MichaelScott",
	'I’m an early bird and a night owl. So I’m wise and have worms.  -MichaelScott',
	'I love inside jokes. I’d love to be a part of one someday.  -MichaelScott',
	'I really should have a tweeter account.  -DwightSchrute',
	'Getting hooked on MegaDesk was my fault. All I care about is Getting More MegaDesk.  -DwightSchrute',
	'WHERE ARE THE TURTLES!?!?!  -MichaelScott',
	'There’s no such thing as an appropriate joke. That’s why it’s called a joke.  -MichaelScott',
	'Don’t ever, for any reason, do anything to anyone, for any reason, ever, no matter what.  -MichaelScott',
	'The only time I set the bar low is for limbo.  -MichaelScott',
	'I… declare…. bankruptcy!  -MichaelScott',
	'You miss 100% of the shots you don’t take.  --Wayne Gretzky  -MichaelScott',
	'Occasionally, I’ll hit someone with my car. So sue me.  -MichaelScott',
	'Why waste time say lot word when few word do trick?  -KevinMalone',
	'Its all about my bonus.  -StanleyHudson',
	'42.7 percent of all statistics are made up on the spot.  -MichaelScott',
	"Supposedly, Recyclops's home planet was destroyed by Polluticons.  -JimHalpert",
	'Get back to me ASAP as possible.  -MichaelScott',
	'Need an ark? I Noah guy.  -MichaelScott',
	'I’m not usually the butt of the joke. I’m usually the face of the joke.  -MichaelScott',
	'I am Beyonce, always.  -MichaelScott',
	'And I will travel to New Zealand. And walk the Lord of the Rings trail to Mordor.  -DwightSchrute',
	'CharDee MacDennis 2: Electric Boogaloo.  -FrankReynolds',
	'RUM-HAMMM!  -FrankReynolds',
	'When I discovered YouTube, I didn’t work for five days.  -MichaelScott',
	'I love catching people in the act. That’s why I always whip open doors.  -DwightSchrute',
	'Always the Padawan, never the Jedi.  -DwightSchrute',
	'Three words: hardworking, alpha male, jackhammer, merciless, insatiable.  -DwightSchrute',
	"I'm not fat... I'm cultivating mass.   -FatMac",
	"You're a master of karate and friendship for everyone.  -Dayman",
	'I say dance, they say, ‘How high?  -MichaelScott',
	'The eyes are the groin of the face.  -DwightSchrute',
	'Hey Goldenface!  -MichaelScarn',
	'Fool me once, strike one. Fool me twice, strike three.  -MichaelScott',
	'This is a dream that I’ve had since lunch… and I’m not giving it up now.  -MichaelScott',
	'I have a lot of questions. Number one, how dare you? -KellyKapoor',
	'Dwigt... Wait, who’s Dwigt?  -DwightSchrute',
	'Would I rather be feared or loved? I want people to be afraid of how much they love me.  -MichaelScott',
	'Identity theft is not a joke, Jim!  -DwightSchrute',
	'Why are you the way that you are?  -MichaelScott',
	'I am fast. I’m somewhere between a snake and a mongoose and a panther.  -DwightSchrute',
	'How is it possible that in five years, I’ve had two engagements and only one chair?  -CreedThoughts',
	'An office is a place where dreams come true.  -MichaelScott',
	'Through concentration, I can raise and lower my cholesterol at will.  -DwightSchrute',
	'Bears. Beets. Battlestar Galactica.   -JimHalpert',
	'That’s what she said.  -MichaelScott',
	"I opened this place after I came back from Vietnam... Ooh, Vietnam. I hear it's lovely.  -MichaelScott",
	'Fight Milk! The first alcoholic dairy based protein drink for bodyguards!  -CharlieKelly',
	'The D.E.N.N.I.S. system.  -DennisReynolds',
	"When Pam gets Michaels old chair, I get Pams old chair. Then I'll have two chairs.  -PamBeesly",
	"Your department's just you, right? Yes, Jim, but I am not easy to manage.  -KellyKapoor",
	'Bipity bopity, gimmie the zopity.  -MichaelScott',
	'Dinkin Flicka.  -DarrylPhilbin',
	'Fluffy-Fingers.  -DarrylPhilbin',
	'The worst thing about prison was the dementors, they were flyin all over the place and were scary.  -PrisonMike',
	'Oh, my resolution was to get more attention.   -KellyKapoor',
	'When someone smiles at me, all I see is a chimpanzee begging for its life.  -DwightSchrute',
	"I'm always thinking one step ahead, like a.. carpenter.. that makes stairs.  -MichaelScott",
	'What was the Dentists name Dwight?  ...Crentist.  -MichaelScott',
	'I talk a lot, so I’ve learned to tune myself out.   -KellyKapoor',
	'I Know NOTHING!!   -MichaelScott',
	'The Michael Scott Paper Company.  -MichaelScott',
	'With great power comes a great electricity bill.  -MichaelScott',
	'You cheated on me? After I specifically asked you not to!?   -MichaelScott',
	'I’m not superstitious, but I am a little stitious.  -MichaelScott',
	'In the end, the greatest snowball isn’t a snowball at all. It’s fear. Merry Christmas.  -DwightSchrute',
	'Beef! It’s what’s for dinner... Who wants some man meat?   -MichaelScott',
	'I overslept. Damn rooster didnt crow.  -DwightSchrute',
	'That is quite the rap sheet, Prison Mike. -And I never got caught neither!  -PrisonMike',
	'Gruel Sandwiches, Gruel Omletes, plus you can eat-cha own hair.  -PrisonMike',
];

module.exports = { comment };
