const fs = require('fs');


let date = new Date();
let t = date.toLocaleTimeString(); // 2:22:09 PM
let d = date.toLocaleDateString(); // 01/03/1984
let timeNow = `${d}  ${t}`;




const badAccounts = ['https://www.instagram.com/hb.iv', 'https://www.instagram.com/lj_brink_'];

//random number function
function r(min, max) {
	return ~~(Math.random() * (max - min + 1) + min);
}

//Function that logs timeStamp + data + \n
function log(data) {
	fs.appendFile('src/log.txt', ` ${data}\n`, () => {
		console.log(`${data}`);
	});
}

// pretends this is a phone not a desktop
const device = {
	name: 'iPhone 12 Pro Max',
	userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1',
	viewport: {
		width: 426,
		height: 926,
		deviceScaleFactor: 3,
		isMobile: true,
		hasTouch: true,
		isLandscape: false,
	},
};
//List of accounts to farm for followers
const targetAccounts = [
	////////////POPULAR BOCA & DELRAY LOCAL PLACES
	/*
	'https://www.instagram.com/downtowndelray/',
	'https://www.instagram.com/visit_delray_beach/',
	'https://www.instagram.com/visitbocaraton/',
	'https://www.instagram.com/bocaratonfl/',
	'https://www.instagram.com/citybocaraton/',
	'https://www.instagram.com/bocapolice/',
	'https://www.instagram.com/delraybeachopen/',
	'https://www.instagram.com/bluefineart/',
	'https://www.instagram.com/sandbardelraybeach/',
	'https://www.instagram.com/new_vegan76/',
	'https://www.instagram.com/restorationlane/',
	'https://www.instagram.com/delraymag/',
	'https://www.instagram.com/renovatewiththeroots/',
	'https://www.instagram.com/mmwooddesigns/',
	'https://www.instagram.com/sassafraswpb/',
	'https://www.instagram.com/realtordotcom/',
	'https://www.instagram.com/sloans_southflorida/',
	'https://www.instagram.com/bocalifemag/',
	'https://www.instagram.com/oldschoolsquaredelray/',
	'https://www.instagram.com/serenitynowstaging/',
	'https://www.instagram.com/cerverare',
	'https://www.instagram.com/livingproof.photography/',
	'https://www.instagram.com/megangribblehome',
	'https://www.instagram.com/jillszedergables/',
	'https://www.instagram.com/flippingahouse/',
	'https://www.instagram.com/landscapeartinc/',
	'https://www.instagram.com/rncbuilders/',
	'https://www.instagram.com/roccostacos/',
	'https://www.instagram.com/delraybeachmarket/',
	'https://www.instagram.com/bodegataqueria/',
	'https://www.instagram.com/thegrovedelrayfl/',
	'https://www.instagram.com/cut432steakhouse/',
	'https://www.instagram.com/theheartofdelraygallery/',
	'https://www.instagram.com/bluefineart/',
	'https://www.instagram.com/artsgaragedelraybeach/',
	'https://www.instagram.com/cornellartmuseum/',
	'https://www.instagram.com/dadadelray/',
	'https://www.instagram.com/elcaminofla/',
	'https://www.instagram.com/lesorellerestaurant/',
	'https://www.instagram.com/deck84_delray/',
	'https://www.instagram.com/parktavernfl/',
	'https://www.instagram.com/brule.bistro/',
	'https://www.instagram.com/habitatforhumanity/',
	'https://www.instagram.com/bocaratonobserver/',
	'https://www.instagram.com/delraybeachgolfclub/',
	'https://www.instagram.com/puttnaround/',
	'https://www.instagram.com/sandowaydiscovery/',
	'https://www.instagram.com/sundy_house/',
/*
	///////Valcatch List
	//////////////////////Builders/Designer/Architects:
		'https://www.instagram.com/verandaestatehomes',
		'https://www.instagram.com/houseofjade',
		'https://www.instagram.com/pikeproperties',
		'https://www.instagram.com/daileyjanssenarcchitects',
		'https://www.instagram.com/architectanddesign',
		'https://www.instagram.com/momentdesign_architecture',
		'https://www.instagram.com/mansionspageforyou',
		'https://www.instagram.com/lush.homes',
		'https://www.instagram.com/luxryious',
		'https://www.instagram.com/successowner',
		'https://www.instagram.com/pool.logic',
		'https://www.instagram.com/vivirdesign',
    
		////////////////////////Bloggers/influencers
		'https://www.instagram.com/malloryervin',
		'https://www.instagram.com/champagneandchanel',
		'https://www.instagram.com/brittanyaldean',
		'https://www.instagram.com/letmetakeyourselfie',
		'https://www.instagram.com/itsmadebybeck',
		'https://www.instagram.com/raelynnofficial',
		'https://www.instagram.com/allexa.anglin ',
    
		////////////////////////Brands/Builder Source:
		'https://www.instagram.com/fergusonshowrooms',
		'https://www.instagram.com/subzeroandwolf ',
		'https://www.instagram.com/kbis_official',
		'https://www.instagram.com/homebuilders ',
		'https://www.instagram.com/buildingsciencefightclub',
		'https://www.instagram.com/awesomeframers',
		'https://www.instagram.com/carpentry_bymar',
		'https://www.instagram.com/finehomebuilding',
		'https://www.instagram.com/mmlighting',
		'https://www.instagram.com/bedrosianstile',
    
		//////////////////////////LOCALS
		'https://www.instagram.com/Visitflorida',
		'https://www.instagram.com/Ftlauderdalesun',
		'https://www.instagram.com/Visit_delray_beach',
		'https://www.instagram.com/Visitbocaraton',
		'https://www.instagram.com/Visitlauderdale',
		'https://www.instagram.com/Downtowndelray',
		'https://www.instagram.com/Palmbeachmoms',
		'https://www.instagram.com/Palmbeachesfl',
		'https://www.instagram.com/Palmbeachcountyfl',
		'https://www.instagram.com/Westpalmbeachflorida',
		'https://www.instagram.com/Visitpalmbeach',
		'https://www.instagram.com/Thebreakers',
		'https://www.instagram.com/Eaupalmbeach',
		*/

	//MEME PAGES
	'https://www.instagram.com/stevecarrelll/',
	'https://www.instagram.com/dwightsdiary/',
	'https://www.instagram.com/rashidajones/',
	'https://www.instagram.com/creedbratton1/',
	'https://www.instagram.com/theofficeisthebestshowever/',
	'https://www.instagram.com/cumsee_adulthumor_/',
	'https://www.instagram.com/dunder_mifflin.munder_difflin/',
	'https://www.instagram.com/dundermemson/',
	'https://www.instagram.com/dundermifflim/',
	'https://www.instagram.com/ratingthememe/',
	'https://www.instagram.com/theme_of_the_memes/',
	'https://www.instagram.com/dundermifflinfeeds/',
	'https://www.instagram.com/dundermifflinpaperco/',
	'https://www.instagram.com/dundermifflintattoos/',
	'https://www.instagram.com/dundersplifflininc/',
	'https://www.instagram.com/theofficefunkopops/',
	'https://www.instagram.com/dwightschrutee/',
	'https://www.instagram.com/dwightschrutemoments/',
	'https://www.instagram.com/goodgirl_badtimes/',
	'https://www.instagram.com/hoegivesnofucks/',
	'https://www.instagram.com/imajokemaker/',
	'https://www.instagram.com/insta.single/',
	'https://www.instagram.com/JimHalpirt/',
	'https://www.instagram.com/memes_quantum/',
	'https://www.instagram.com/memetheme1/',
	'https://www.instagram.com/michaelsmanymoods/',
	'https://www.instagram.com/stevecarrelll/',
	'https://www.instagram.com/stevecarrelll/',
	'https://www.instagram.com/office.obsession/',
	'https://www.instagram.com/officephotos/',
	'https://www.instagram.com/officethememes/',
	'https://www.instagram.com/stevecarrelll/',
	'https://www.instagram.com/pambeesle/',
	'https://www.instagram.com/queen.catto/',
	'https://www.instagram.com/savage_memes_only/',
	'https://www.instagram.com/stevecarrelll/',
	'https://www.instagram.com/tequilashots/',
	'https://www.instagram.com/textpostgiant/',
	'https://www.instagram.com/the.office.alliance/',
	'https://www.instagram.com/phatmemer/',
	'https://www.instagram.com/thegainz/',
	'https://www.instagram.com/theoffice/',
	'https://www.instagram.com/theofficeismycrack/',
	'https://www.instagram.com/theofficememers/',
	'https://www.instagram.com/tumblermemes/',
	'https://www.instagram.com/wholesometroll/',
	'https://www.instagram.com/worstigaccount/',


	//list Targeting WOMEN 
	'https://www.instagram.com/boandtee/',
	'https://www.instagram.com/revolve/',
	'https://www.instagram.com/revolvebeauty/',
	'https://www.instagram.com/maccosmetics/',
	'https://www.instagram.com/ohpolly/',
	'https://www.instagram.com/ohpollyswim/',
	'https://www.instagram.com/pallascouture/',
	'https://www.instagram.com/pallascollective/',
	'https://www.instagram.com/studio.albus/',
	'https://www.instagram.com/seduction_la/',
	'https://www.instagram.com/fuckologyofficial/',
	'https://www.instagram.com/betchwithnolife/',
	'https://www.instagram.com/basic/',
	'https://www.instagram.com/bipolar_girlfriend_/',
	'https://www.instagram.com/ohmboutique/',
	'https://www.instagram.com/yourbreakupbestie/',
	'https://www.instagram.com/sahirajewelrydesign/',
	'https://www.instagram.com/okb_int/',
	'https://www.instagram.com/cottononbody/',
	'https://www.instagram.com/lv_perfection_medspa/',
	'https://www.instagram.com/berrybeachyswimwear/',
	'https://www.instagram.com/callherdaddy/',
	'https://www.instagram.com/bangn.body/',
	'https://www.instagram.com/lovetrends.shop/',
	'https://www.instagram.com/glossy_zodiac/',
	'https://www.instagram.com/bossbabe.inc/',

	/*LIST TARGETING MEN - ONLYFANS
	'https://www.instagram.com/mandi_lynn_bbw/',
	'https://www.instagram.com/therealnatashatosini/',
	'https://www.instagram.com/jaidexoxo_/',
	'https://www.instagram.com/ivykiaraofficial/',
	'https://www.instagram.com/tatted.mama44/',
	'https://www.instagram.com/officialmakaylaalt/',
	'https://www.instagram.com/amberleighhh/',
	'https://www.instagram.com/devin.meow/',
	'https://www.instagram.com/jessicakes33/',
	'https://www.instagram.com/jessicacakes2/',
	'https://www.instagram.com/jessicafitcake/',
	'https://www.instagram.com/millenawhite/',
	'https://www.instagram.com/_lucky_ladybird/',
	'https://www.instagram.com/millena_white/',
	'https://www.instagram.com/missjessarhodes/',
	'https://www.instagram.com/fierysireniv/',
	'https://www.instagram.com/egoistqaa/',
	'https://www.instagram.com/liubov_kalish/',
	'https://www.instagram.com/lsdiamonds69/',
	*/
];

let comment = [

	'I underestimated you Michael. Yea, well maybe next time, you better estimate me.  -MichaelScott',
	'Live and let live. Im not familiar with that expression. Its a James Bond.  -MichaelScott',
	'I like this chair, it offers good support and is ErckleNomickly correct.  -MichaelScott',
	'I went to the park tryna feed the pigeons. I guess they all flew west for the winter.  -MichaelScott',
	'They are in for a bitter suprise... I am not to be truffled with.  -MichaelScott',
	'Remember, They are trying to make me an escape goat.  -MichaelScott',
	'You all encouraged it! You were complissit! You are all successories!  -MichaelScott',
	'This is like the Blair ..Witch ..Hunt ..Project.  -MichaelScott',
	'Jim halpert is smudge and arrogant... I think you mean smug.  Theres that arrogance.  -MichaelScott',
	'And it is up to me... to get rid of the curse... that hit meredith with my car.  -MichaelScott',
	'Nailed it!  -andybernard',
	'Dont drop the soap! Dont drop the soap!  -Prisonmike',
	'And you my friend, would be... Da Bell-Of-Da-Ball  -PrisonMike',
	"You know, stuff like.. 'Fleece it out' and 'Going mach five.'  -DarrylPhilbin",
	'Well well well, how the turntables.  -MichaelScott',
	'Webster’s Dictionary defines wedding as.. the fusing of two metals with a hot torch.  -MichaelScott',
	'Who is Justice Beaver?  -DwightSchrute',
	'I am faster than 80 percent of all snakes.  -DwightSchrute',
	'Bears...Beats...Battlestar Galactica.  -JimHalpert',
	'Hi, I’m Date Mike. Nice to meet me.  -MichaelScott',
	'Which Bear is Best?  -DwightSchrute',
	"Sometimes I start a sentence, without knowing where it's going. I just hope I find it along the way.  -MichaelScott",
	'Bread is the paper of the food industry. You write your sandwich on it.  -DwightSchrute',
	'Ain’t no party like a Scranton party cause a Scranton party don’t stop!  -MichaelScott',
	'Bob Vance, Vance Refrigeration.   -BobVance',
	'Break me off a piece of that app-le-sauce.   -AndyBernard',
	"Now, let's say you and I go toe-to-toe on bird law... and see who comes out the victor.  -CharlieKelly",
	'We are at Threat Level Midnight.  -MichaelScott',
	'Cause... Science is a liar, sometimes.   -FatMac',
	'I love my employees even though I hit one of you with my car.  -MichaelScott',
	'When the king of Nigeria emails you directly, asking for help, you help.  -MichaelScott',
	'Rit-dit-dit-doooo!   -AndyBernard',
	'This is ham, soaked in rum... RUM-HAM!   -FrankReynolds',
	"Shadynasty's Jazz Club.   -FrankReynolds",
	'Fight Milk! The first alcoholic dairy based protein drink for bodyguards!   -Charliekelly',
	'Parkor... Hardcore Parkor!  -MichaelScott',
	'Jim and I are great friends. We hang out a ton, mostly at work.  -MichaelScott',
	"White-collar and blue-collar. I don’t see it that way... Cause I'm collar blind.  -MichaelScott",
	'I’m an early bird and a night owl. So I’m wise and have worms.  -MichaelScott',
	'I love inside jokes. I’d love to be a part of one someday.  -MichaelScott',
	'I really should have a tweeter account.  -DwightSchrute',
	'Getting hooked on MegaDesk was my fault. All I care about is Getting More MegaDesk.  -DwightSchrute',
	'WHERE ARE THE TURTLES!?!?!  -MichaelScott',
	'There’s no such thing as an appropriate joke. That’s why it’s called a joke.  -MichaelScott',
	'Don’t ever, for any reason, do anything to anyone, for any reason, ever, no matter what.  -MichaelScott',
	'The only time I set the bar low is for limbo.  -MichaelScott',
	'I… declare…. bankruptcy!  -MichaelScott',
	'You miss 100% of the shots you don’t take.  --Wayne Gretzky  -MichaelScott',
	'Occasionally, I’ll hit someone with my car. So sue me.  -MichaelScott',
	'Why waste time say lot word when few word do trick?  -KevinMalone',
	'Its all about my bonus.  -StanleyHudson',
	'42.7 percent of all statistics are made up on the spot.  -MichaelScott',
	"Supposedly, Recyclops's home planet was destroyed by Polluticons.  -JimHalpert",
	'Get back to me ASAP as possible.  -MichaelScott',
	'Need an ark? I Noah guy.  -MichaelScott',
	'I’m not usually the butt of the joke. I’m usually the face of the joke.  -MichaelScott',
	'I am Beyonce, always.  -MichaelScott',
	'And I will travel to New Zealand. And walk the Lord of the Rings trail to Mordor.  -DwightSchrute',
	'CharDee MacDennis 2: Electric Boogaloo.  -FrankReynolds',
	'RUM-HAMMM!  -FrankReynolds',
	'When I discovered YouTube, I didn’t work for five days.  -MichaelScott',
	'I love catching people in the act. That’s why I always whip open doors.  -DwightSchrute',
	'Always the Padawan, never the Jedi.  -DwightSchrute',
	'Three words: hardworking, alpha male, jackhammer, merciless, insatiable.  -DwightSchrute',
	"I'm not fat... I'm cultivating mass.   -FatMac",
	"You're a master of karate and friendship for everyone.  -Dayman",
	'I say dance, they say, ‘How high?  -MichaelScott',
	'The eyes are the groin of the face.  -DwightSchrute',
	'Hey Goldenface!  -MichaelScarn',
	'Fool me once, strike one. Fool me twice, strike three.  -MichaelScott',
	'This is a dream that I’ve had since lunch… and I’m not giving it up now.  -MichaelScott',
	'I have a lot of questions. Number one, how dare you? -KellyKapoor',
	'Dwigt... Wait, who’s Dwigt?  -DwightSchrute',
	'Would I rather be feared or loved? I want people to be afraid of how much they love me.  -MichaelScott',
	'Identity theft is not a joke, Jim!  -DwightSchrute',
	'Why are you the way that you are?  -MichaelScott',
	'I am fast. I’m somewhere between a snake and a mongoose and a panther.  -DwightSchrute',
	'How is it possible that in five years, I’ve had two engagements and only one chair?  -CreedThoughts',
	'An office is a place where dreams come true.  -MichaelScott',
	'Through concentration, I can raise and lower my cholesterol at will.  -DwightSchrute',
	'Bears. Beets. Battlestar Galactica.   -JimHalpert',
	'That’s what she said.  -MichaelScott',
	"I opened this place after I came back from Vietnam... Ooh, Vietnam. I hear it's lovely.  -MichaelScott",
	'Fight Milk! The first alcoholic dairy based protein drink for bodyguards!  -CharlieKelly',
	'The D.E.N.N.I.S. system.  -DennisReynolds',
	"When Pam gets Michaels old chair, I get Pams old chair. Then I'll have two chairs.  -PamBeesly",
	"Your department's just you, right? Yes, Jim, but I am not easy to manage.  -KellyKapoor",
	'Bipity bopity, gimmie the zopity.  -MichaelScott',
	'Dinkin Flicka.  -DarrylPhilbin',
	'Fluffy-Fingers.  -DarrylPhilbin',
	'The worst thing about prison was the dementors, they were flyin all over the place and were scary.  -PrisonMike',
	'Oh, my resolution was to get more attention.   -KellyKapoor',
	'When someone smiles at me, all I see is a chimpanzee begging for its life.  -DwightSchrute',
	"I'm always thinking one step ahead, like a.. carpenter.. that makes stairs.  -MichaelScott",
	'What was the Dentists name Dwight?  ...Crentist.  -MichaelScott',
	'I talk a lot, so I’ve learned to tune myself out.   -KellyKapoor',
	'I Know NOTHING!!   -MichaelScott',
	'The Michael Scott Paper Company.  -MichaelScott',
	'With great power comes a great electricity bill.  -MichaelScott',
	'You cheated on me? After I specifically asked you not to!?   -MichaelScott',
	'I’m not superstitious, but I am a little stitious.  -MichaelScott',
	'In the end, the greatest snowball isn’t a snowball at all. It’s fear. Merry Christmas.  -DwightSchrute',
	'Beef! It’s what’s for dinner... Who wants some man meat?   -MichaelScott',
	'I overslept. Damn rooster didnt crow.  -DwightSchrute',
	'That is quite the rap sheet, Prison Mike. -And I never got caught neither!  -PrisonMike',
	'Gruel Sandwiches, Gruel Omletes, plus you can eat-cha own hair.  -PrisonMike',

];

module.exports = { targetAccounts, device, timeNow, r, log, badAccounts, comment };

// let currenturl = 'https://www.instagram.com/hb.iv';
// let searchResult = badAccounts.includes(currenturl);
// if (!searchResult) {
// 	console.log('no bad accoutns found ' + searchResult);
// } else {
// 	console.log('badAccounts found ' + searchResult);
// }
