const { r } = require('./helpers');
const fs = require('fs');

const memeAccounts = [
	// Office

	'https://www.instagram.com/glossy_zodiac',

	'https://www.instagram.com/dwightsdiary/',
	'https://www.instagram.com/glossy_zodiac',
	'https://www.instagram.com/memestheoffice/',
	'https://www.instagram.com/glossy_zodiac',
	'https://www.instagram.com/jimhalpert/',
	'https://www.instagram.com/tobyflendersson/',
	'https://www.instagram.com/dwightchrute/',
	'https://www.instagram.com/theoffices/',
	'https://www.instagram.com/glossy_zodiac',
	'https://www.instagram.com/glossy_zodiac',
	'https://www.instagram.com/stevecarrelll/',
	'https://www.instagram.com/dwightschrutemoments/',
	'https://www.instagram.com/theofficeisthebestshowever/',
	'https://www.instagram.com/glossy_zodiac',
	'https://www.instagram.com/theofficeismycrack/',
	'https://www.instagram.com/glossy_zodiac',
	'https://www.instagram.com/theofficememers/',
	'https://www.instagram.com/dwightschrutee/',
	'https://www.instagram.com/glossy_zodiac',
	'https://www.instagram.com/dunder_mifflin.munder_difflin/',
	'https://www.instagram.com/dundermifflinpaperco/',
	'https://www.instagram.com/dundermifflintattoos/',
	'https://www.instagram.com/JimHalpirt/',
	'https://www.instagram.com/michaelsmanymoods/',
	'https://www.instagram.com/glossy_zodiac',
	'https://www.instagram.com/office.obsession/',
	'https://www.instagram.com/officephotos/',
	'https://www.instagram.com/officethememes/',
	'https://www.instagram.com/glossy_zodiac',
	'https://www.instagram.com/pambeesle/',
	'https://www.instagram.com/the.office.alliance/',
	/*
	// Meme pages
	'https://www.instagram.com/memetheme1/',
	'https://www.instagram.com/queen.catto/',
	'https://www.instagram.com/savage_memes_only/',
	'https://www.instagram.com/tequilashots/',
	'https://www.instagram.com/textpostgiant/',
	'https://www.instagram.com/phatmemer/',
	'https://www.instagram.com/insta.single/',
	'https://www.instagram.com/ratingthememe/',
	'https://www.instagram.com/tumblermemes/',
	'https://www.instagram.com/wholesometroll/',
	'https://www.instagram.com/worstigaccount/',
	'https://www.instagram.com/fuckologyofficial/',
	'https://www.instagram.com/glossy_zodiac/',
	'https://www.instagram.com/cumsee_adulthumor_/',
	/*
		
	//LIST TARGETING MEN - ONLYFANS
	'https://www.instagram.com/mandi_lynn_bbw/',
	'https://www.instagram.com/therealnatashatosini/',
	'https://www.instagram.com/jaidexoxo_/',
	'https://www.instagram.com/ivykiaraofficial/',
	'https://www.instagram.com/tatted.mama44/',
	'https://www.instagram.com/officialmakaylaalt/',
	'https://www.instagram.com/amberleighhh/',
	'https://www.instagram.com/devin.meow/',
	'https://www.instagram.com/jessicakes33/',
	'https://www.instagram.com/jessicacakes2/',
	'https://www.instagram.com/jessicafitcake/',
	'https://www.instagram.com/millenawhite/',
	'https://www.instagram.com/_lucky_ladybird/',
	'https://www.instagram.com/millena_white/',
	'https://www.instagram.com/missjessarhodes/',
	'https://www.instagram.com/fierysireniv/',
	'https://www.instagram.com/egoistqaa/',
	'https://www.instagram.com/liubov_kalish/',
	'https://www.instagram.com/lsdiamonds69/',
	*/
];

const memeTags = [
	'#funny',
	'#lol',
	'#meme',
	'#memes',
	'#dankmemes',
	'#offensivememes',
	'#danker',
	'#epic',
	'#jokes',
	'#memelord',
	'#dailymemes',
	'#haha',
	'#edgymeme',
	'#memepage',
	'#humor',
	'#spicymemes',
	'#funnymeme',
	'#lmao',
	'#memesdaily',
	'#funnymemes',
	'#memeoftheday',
	'#memez',
	'#edgymemes',
	'#laugh',
	'#stupid',
	'#joking',
	'#relatable',
	'#crazy',
	'#bestmemes',
	'#memegod',
	'#insane',
	'#savagememes',
	'#nochill',
	'#offensive',
	'#rofl',
	'#funnyvideos',
	'#hilariousmemes',
	'#cringe',
	'#lmfao',
	'#dankmemesdaily',
	'#dumb',
	'#bruh',
	'#silly',
	'#memepages',
	'#memestagram',
	'#memer',
	'#damn',
	'#dankest',
	'#dankmemez',
	'#memesfordays',
	'#goodmemes',
	'#funniestmemes',
	'#memesrlife',
	'#spongebobmemes',
	'#justforfun',
	'#funnypics',
	'#reddit',
	'#jokesfordays',
	'#memesquad',
	'#memestar',
	'#darkmemes',
	'#stolenmemes',
	'#cringememes',
	'#ironicmemes',
	'#redditmemes',
	'#thuglife',
	'#funnymemesdaily',
	'#memedaily',
	'#memeaccount',
	'#memetime',
	'#deepfriedmemes',
	'#lolz',
	'#darkhumor',
	'#dankestmemes',
	'#dankvideos',
	'#laughoutloud',
	'#offensivememe',
	'#viralmemes',
	'#instamemes',
	'#pettypost',
	'#dailymeme',
	'#freshmemes',
	'#hoodmemes',
	'#shitpost',
	'#comedy',
	'#tiktok',
	'#shitposting',
	'#bhfyp',
	'#love',
	'#fun',
	'#instagram',
	'#instagood',
	'#dank',
	'#edgy',
	'#explorepage',
	'#dankmeme',
	'#ol',
	'#explore',
	'#likeforlikes',
	'#art',
	'#photography',
	'#viral',
	'#hilarious',
	'#cute',
	'#photooftheday',
	'#aesthetic',
	'#music',
	'#desimemes',
	'#mobilelegends',
	'#fashion',
	'#funnyshit',
	'#instadaily',
	'#funnyposts',
	'#cannabis',
	'#gamer',
	'#indianmemes',
	'#gaming',
	'#youtube',
	'#sarcasm',
	'#igmemes',
	'#mlbb',
	'#life',
	'#sarcasticmemes',
	'#smile',
	'#f',
	'#nature',
	'#dogsofinstagram',
	'#grunge',
	'#game',
	'#friends',
	'#beautiful',
	'#happy',
	'#dog',
	'#trending',
	'#mobilelegendswtf',
	'#edit',
	'#relatablememes',
	'#skate',
	'#filthyfrank',
	'#shitpostchile',
	'#bakchodi',
	'#mobilelegendsbangbang',
	'#travel',
	'#420',
	'#hiphop',
	'#doglovers',
	'#doggo',
	'#skateboard',
	'#tumblr',
	'#dogsandpals',
	'#dogoftheday',
	'#aviation',
	'#joke',
	'#funnyjokes',
	'#comedyvideo',
	'#bollywood',
	'#kollywood',
	'#dance',
	'#naturephotography',
	'#sunset',
	'#memesespañol',

	'#savage',
	'#edgymemesforedgyteens',
	'#dankbar',
	'#dankmemescanmeltsteelbeams',
	'#dankmemescantmeltsteelbeams',
	'#dankbarkeit',
	'#danke',
	'#21savage',
	'#tiwasavage',

	'#memesbrasil',
	'#animememes',
	'#fortnitememes',
	'#memeblr',
	'#btsmemes',
	'#memesgraciosos',
	'#memesbrasileiros',
	'#tiktokmemes',
	'#memesbr',
	'#nichememes',
	'#memesenespañol',
	'#freefirememes',
	'#pubgmemes',
	'#wholesomememes',
	'#kpopmemes',
	'#tamilmemes',
	'#memes4days',
	'#memesdank',
	'#memess',
	'#bollywoodmemes',
	'#memeschile',
	'#memes2good',
	'#gamingmemes',
	'#memesargentina',
	'#memester',
	'#adultmemes',
	'#memesforlife',
	'#gainwithlarrymemes',
	'#memesespa',
	'#cancerousmemes',
	'#memestgram',
	'#memeslatinos',
	'#cancermemes',
	'#memeschilenos',
	'#twittermemes',

	'#memesita',
	'#gymmemes',
	'#ramadankareem',
	'#sillymemes',
	'#immortalmemes',
	'#memeslayer',
	'#memesfunny',
	'#weebmemes',
	'#memesindia',
	'#animemes',
	'#autisticmemes',
	'#nicememes',
	'#kenyanmemes',
	'#weedmemes',
	'#wtfmemes',
	'#robloxmemes',
	'#lovememes',
	'#gedanken',
	'#videomemes',
	'#schoolmemes',
	'#dylanteromemes',
	'#vadivelumemes',
	'#catmemes',
	'#comedymemes',
	'#cursedmemes',
	'#narutomemes',
	'#chilememes',
	'#joyfulmamas',
	'#starwarsmemes',
	'#cutememes',
	'#fortnitebattleroyalememes',
	'#lolmemes',
	'#epicmemes',
	'#trendingmemes',
	'#gujjumemes',
	'#crushmemes',
	'#gaymemes',
	'#indianmemesdaily',
	'#yeetmemes',
	'#footballmemes',
	'#dogmemes',
	'#nbamemes',
	'#leagueoflegendsmemes',
	'#gamermemes',
	'#newmemes',
	'#originalmemes',
	'#relationshipmemes',
	'#weirdmemes',
	'#codmemes',

	'#deadmemes',
	'#marvelmemes',
	'#dark',
	'#darker',
	'#darkest',
	'#darkaesthetic',
	'#funnyquotes',

	'#funnycats',
	'#darkgrunge',
	'#funnydogs',
	'#darksouls',
	'#funnypictures',
	'#darkartist',
	'#darkacademia',
	'#funnyanimals',
	'#darkness',
	'#funnycat',
	'#darkskin',
	'#darkfashion',
	'#darkchocolate',
	'#funnyvids',
	'#darkhair',
	'#funnytweets',
	'#funnypost',
	'#funnytextpost',
	'#funnytextposts',
	'#funnydog',
	'#funnyvines',
	'#funnymoments',
	'#funnyaf',
	'#funnyreels',
	'#darkphotography',
	'#funnypic',
	'#darkside',
	'#instafunny',
	'#pubgfunny',
	'#funnyface',
	'#funnyfaces',
	'#toofunny',
	'#funnytumblr',
	'#darkknight',
	'#ifunny',
	'#funnyday',
	'#funnystuff',
	'#fortnitefunny',
	'#alternative',
	'#light',
	'#anotherdayintheoffice',
	'#backoffice',
	'#backtotheoffice',
	'#coworkingoffice',
	'#dayattheoffice',
	'#dwightkschrute',
	'#dwightschruteapproved',
	'#dwightschrutebobblehead',
	'#dwightschrutecosplay',
	'#dwightschrutecostume',
	'#dwightschrutee',
	'#dwightschruteedit',
	'#dwightschruteedits',
	'#dwightschrutefanart',
	'#dwightschruteforever',
	'#dwightschruteforpresident',
	'#dwightschrutegymformuscles',
	'#dwightschrutehair',
	'#dwightschruteismyspiritanimal',
	'#dwightschrutememe',
	'#dwightschrutememes',
	'#dwightschrutequotes',
	'#dwightschrutesgymformuscles',
	'#dwightschrutetattoo',
	'#dwightschrutetheoffice',
	'#dwightschrutewouldbeproud',
	'#dwightshrute',
	'#frontoffice',
	'#gardenoffice',
	'#greenoffice',
	'#harddayattheoffice',
	'#headoffice',
	'#homeofficegoals',
	'#homeofficelife',
	'#instaoffice',
	'#loanofficers',
	'#michael_scott',
	'#michaelgaryscott',
	'#michaelscott2020',
	'#michaelscottartist',
	'#michaelscottedit',
	'#michaelscottedits',
	'#michaelscottfanart',
	'#michaelscottfanclub',
	'#michaelscottforever',
	'#michaelscottforpresident',
	'#michaelscottislife',
	'#michaelscottisms',
	'#michaelscottismyhero',
	'#michaelscottismyspiritanimal',
	'#michaelscottleavesdundermifflin',
	'#michaelscottmarch',
	'#michaelscottmeme',
	'#michaelscottmemes',
	'#michaelscottmoment',
	'#michaelscottmonday',
	'#michaelscottmondays',
	'#michaelscottmoore',
	'#michaelscottpapercompany',
	'#michaelscottpapercompanyinc',
	'#michaelscottphotography',
	'#michaelscottquote',
	'#michaelscottquotes',
	'#michaelscotttheoffice',
	'#michaelscottwisdom',
	'#microsoftoffice',
	'#mofficer',
	'#myofficetoday',
	'#myofficeview',
	'#nursesoffice',
	'#office_time',
	'#officeaccessories',
	'#officeassistant',
	'#officebag',
	'#officebags',
	'#officeboy',
	'#officebreak',
	'#officebuddies',
	'#officebuildings',
	'#officechairs',
	'#officechristmasparty',
	'#officeclothes',
	'#officecolleagues',
	'#officeculture',
	'#officedays',
	'#officedelivery',
	'#officedepot',
	'#officedoglife',
	'#officedogsofinstagram',
	'#officeenvy',
	'#officeevent',
	'#officefitout',
	'#officefriends',
	'#officehour',
	'#officehours',
	'#officehumor',
	'#officelifestyle',
	'#officelove',
	'#officemanagement',
	'#officemanager',
	'#officemood',
	'#officeoffice',
	'#officeparties',
	'#officepet',
	'#officeplant',
	'#officepranks',
	'#officeproblems',
	'#officepup',
	'#officeromance',
	'#officescenes',
	'#officesetup',
	'#officeshenanigans',
	'#officeshirt',
	'#officesnacks',
	'#officesnapshots',
	'#officesyndrome',
	'#officeteam',
	'#officetreats',
	'#officetrip',
	'#officeworks',
	'#officeyoga',
	'#schrute',
	'#schrutefarms',
	'#scottmichael',
	'#scottmichaelackerman',
	'#scottmichaelart',
	'#scottmichaels',
	'#smartoffice',
	'#the_office',
	'#the_office_expo',
	'#the_office_freak',
	'#theofficeart',
	'#theofficeblinddate',
	'#theofficebloopers',
	'#theofficebr',
	'#theofficebrasil',
	'#theofficecabo',
	'#theofficecake',
	'#theofficeclips',
	'#theofficecookies',
	'#theofficedeletedscenes',
	'#theofficeedit',
	'#theofficeedits',
	'#theofficefacts',
	'#theofficefanart',
	'#theofficefans',
	'#theofficeforever',
	'#theofficefreicaneca',
	'#theofficefunkopops',
	'#theofficefunny',
	'#theofficegroup',
	'#theofficeindia',
	'#theofficejokes',
	'#theofficeladies',
	'#theofficeladiespodcast',
	'#theofficeletters',
	'#theofficememe',
	'#theofficememesfunny',
	'#theofficemiami1',
	'#theofficemoments',
	'#theofficemusical',
	'#theofficenbc',
	'#theofficereunion',
	'#theofficerp',
	'#theofficescenes',
	'#theofficetattoo',
	'#theofficetattoos',
	'#theofficetrivia',
	'#theofficetvshow',
	'#theofficeuk',
	'#theofficeusa',
	'#theofficevideos',
	'#theusoffice',
];

const memeComments = [

	'Wanker',
	'Porker',
	'Geezer',
	'Spastic',
	'Doorknob',
	'Lickspittle',
	'Pillock',
	'Ninnyhammer',
	'Mumpsimus',
	'Milksop',
	'Hobbledehoy',
	'Pettifogger',
	'Mooncalf',
	'Saltimbanco',
	'Bumfuzzle',
	'Fartlek',
	'Everywhen',
	'Erf',
	'Hullaballoo',
	'Meldrop',
	'Obelus',
	'Sozzled',
	'Bumbershoot',
	'Smicker',
	'Cleek',
	'Whippersnapper',
	'Salopettes',
	'Bibliokept',
	'Accubation',
	'Lollygag',
	'Abecedarian',
	'Bamboozled',
	'Flabbergast',
	'Fappish',
	'Cattywampus',
	'Noob',
	'Octothorpe',
	'Schmoozed',
	'Smaze',
	'Waesucks',
	'Widdershins',
	'Blubber',
	'Dollop',
	'Festooned',
	'Duddish',
	'Gobbledygook',
	'Hodgepodge',
	'Ramshackle',
	'Flummoxed',
	'Gardyloo',
	'Collywobbles',
	'Billingsgate',
	'Slumgullion',
	'Willie',
	'Conjubilant ',
	'Futz',
	'Flibbertigibbet',
	'Frippery',
	'Pamby',
	'Diphthong',
	'Wamble',
	'Geebung',
	'Teazel',
	'Kibitzer',
	'Phablet',
	'Mollycoddle',
	'Ragamuffin',
	'Snickersnee',
	'Piffle',
	'Bugaboo',
	'Scallywag',
	'Teetotaler',
	'Skedaddle',
	'Wampum',
	'Sleenwort',
	'Taradiddle',
	'Whirligig',
	'Yitten',
	'Ratoon',
	'Dingus',
	'Pronk',
	'Hogwash',
	'Bupkis',
	'Fipple',
	'Aloof',
	'Yooper',
	'Squeegee',
	'Doohickey',
	'Cabotage',
	'Deckled',
	'Frou',
	'Ballyhoo',
	'Abear',
	'Whiffler',
	'Hoodwink',
	'Stumblebum',
	'Unperson',
	'Doozy',
	'Nearly',
	'Fairly',
	'Kind Of',
	'Kindly ',
	'Moderately',
	'More Or Less',
	'Quite',
	'Rather',
	'Relatively',
	'Somewhat',
	'Auxiliary',
	'Inessential',
	'Nonessential',
	'Secondary',
	'Unnecessary',
	'Extra',
	'Peripheral',
];

const postComments = [
	'I underestimated you Michael. Yea, well maybe next time, you better estimate me.  ',
	'Live and let live. Im not familiar with that expression. Its a James Bond.  ',
	'I like this chair, it offers good support and is ErckleNomickly correct.  ',
	'I went to the park tryna feed the pigeons. I guess they all flew west for the winter.  ',
	'They are in for a bitter suprise... I am not to be truffled with.  ',
	'Remember, They are trying to make me an escape goat.  ',
	'You all encouraged it! You were complissit! You are all successories!  ',
	'This is like the Blair ..Witch ..Hunt ..Project.  ',
	'Jim halpert is smudge and arrogant... I think you mean smug.  Theres that arrogance.  ',
	'And it is up to me... to get rid of the curse... that hit meredith with my car.  ',
	'Nailed it!  ',
	'Dont drop the soap! Dont drop the soap!  ',
	'And you my friend, would be... Da Bell-Of-Da-Ball  ',
	"You know, stuff like.. 'Fleece it out' and 'Going mach five.'  ",
	'Well well well, how the turntables.  ',
	"Webster's Dictionary defines wedding as.. the fusing of two metals with a hot torch.  ",
	'Who is Justice Beaver?  ',
	'I am faster than 80 percent of all snakes.  ',
	'Bears...Beats...Battlestar Galactica.  ',
	"Hi, I'm Date Mike. Nice to meet me.  ",
	'Which Bear is Best?  ',
	"Sometimes I start a sentence, without knowing where it's going. I just hope I find it along the way.  ",
	'Bread is the paper of the food industry. You write your sandwich on it.  ',
	"Ain't no party like a Scranton party cause a Scranton party don't stop!  ",
	'Bob Vance, Vance Refrigeration.   ',
	'Break me off a piece of that app-le-sauce.   ',
	"Now, let's say you and I go toe-to-toe on bird law... and see who comes out the victor.  ",
	'We are at Threat Level Midnight.  ',
	'Cause... Science is a liar, sometimes.   ',
	'I love my employees even though I hit one of you with my car.  ',
	'When the king of Nigeria emails you directly, asking for help, you help.  ',
	'Rit-dit-dit-doooo!   ',
	'This is ham, soaked in rum... RUM-HAM!   ',
	"Shadynasty's Jazz Club.   ",
	'Fight Milk! The first alcoholic dairy based protein drink for bodyguards!   ',
	'Parkor... Hardcore Parkor!  ',
	'Jim and I are great friends. We hang out a ton, mostly at work.  ',
	"White-collar and blue-collar. I don't see it that way... Cause I'm collar blind.  ",
	"I'm an early bird and a night owl. So I'm wise and have worms.  ",
	"I love inside jokes. I'd love to be a part of one someday.  ",
	'I really should have a tweeter account.  ',
	'Getting hooked on MegaDesk was my fault. All I care about is Getting More MegaDesk.  ',
	'WHERE ARE THE TURTLES!?!?!  ',
	"There's no such thing as an appropriate joke. That's why it's called a joke.  ",
	"Don't ever, for any reason, do anything to anyone, for any reason, ever, no matter what.  ",
	'The only time I set the bar low is for limbo.  ',
	'I… declare…. bankruptcy!  ',
	"You miss 100% of the shots you don't take. ",
	"Occasionally, I'll hit someone with my car. So sue me.  ",
	'Why waste time say lot word when few word do trick?  ',
	'Its all about my bonus.  ',
	'42.7 percent of all statistics are made up on the spot.  ',
	"Supposedly, Recyclops's home planet was destroyed by Polluticons.  ",
	'Get back to me ASAP as possible.  ',
	'Need an ark? I Noah guy.  ',
	"I'm not usually the butt of the joke. I'm usually the face of the joke.  ",
	'I am Beyonce, always.  ',
	'And I will travel to New Zealand. And walk the Lord of the Rings trail to Mordor.  ',
	'CharDee MacDennis 2: Electric Boogaloo.  ',
	'RUM-HAMMM!  ',
	"When I discovered YouTube, I didn't work for five days.  ",
	"I love catching people in the act. That's why I always whip open doors.  ",
	'Always the Padawan, never the Jedi.  ',
	'Three words: hardworking, alpha male, jackhammer, merciless, insatiable.  ',
	"I'm not fat... I'm cultivating mass.   ",
	"You're a master of karate and friendship for everyone.  ",
	'I say dance, they say, How high?  ',
	'The eyes are the groin of the face.  ',
	'Hey Goldenface!  ',
	'Fool me once, strike one. Fool me twice, strike three.  ',
	"This is a dream that I've had since lunch… and I'm not giving it up now.  ",
	'I have a lot of questions. Number one, how dare you? ',
	"Dwigt... Wait, who's Dwigt?  ",
	'Would I rather be feared or loved? I want people to be afraid of how much they love me.  ',
	'Identity theft is not a joke, Jim!  ',
	'Why are you the way that you are?  ',
	"I am fast. I'm somewhere between a snake and a mongoose and a panther.  ",
	"How is it possible that in five years, I've had two engagements and only one chair?",
	'An office is a place where dreams come true.  ',
	'Through concentration, I can raise and lower my cholesterol at will.  ',
	'Bears. Beets. Battlestar Galactica.   ',
	"That's what she said.  ",
	"I opened this place after I came back from Vietnam... Ooh, Vietnam. I hear it's lovely.  ",
	'Fight Milk! The first alcoholic dairy based protein drink for bodyguards!  ',
	'The D.E.N.N.I.S. system.  ',
	"When Pam gets Michaels old chair, I get Pams old chair. Then I'll have two chairs.  ",
	"Your department's just you, right? Yes, Jim, but I am not easy to manage.  ",
	'Bipity bopity, gimmie the zopity.  ',
	'Dinkin Flicka.  ',
	'Fluffy-Fingers.  ',
	'The worst thing about prison was the dementors, they were flyin all over the place and were scary.  ',
	'Oh, my resolution was to get more attention.   ',
	'When someone smiles at me, all I see is a chimpanzee begging for its life.  ',
	"I'm always thinking one step ahead, like a.. carpenter.. that makes stairs.  ",
	'What was the Dentists name Dwight?  ...Crentist.  ',
	"I talk a lot, so I've learned to tune myself out.   ",
	'I Know NOTHING!!   ',
	'The Michael Scott Paper Company.  ',
	'With great power comes a great electricity bill.  ',
	'You cheated on me? After I specifically asked you not to!?   ',
	"I'm not superstitious, but I am a little stitious.  ",
	"In the end, the greatest snowball isn't a snowball at all. It's fear. Merry Christmas.  ",
	"Beef! It's what's for dinner... Who wants some man meat?   ",
	'I overslept. Damn rooster didnt crow.  ',
	'That is quite the rap sheet Prison Mike. And I never got caught neither. ',
	'Gruel Sandwiches, Gruel Omletes, plus you can eat ya own hair. ',
];

const tags30 = memeTags
	.sort(() => Math.random() - Math.random())
	.slice(0, 27)
	.toString()
	.replace(/\,/g, ' ');
const fullCaption = `${postComments[r(0, postComments.length)]}`;

// let farmAccount = r(1, memeAccounts.length);
// console.log(farmAccount);

module.exports = { memeAccounts, fullCaption };
